#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  📡 STREAM RECORDER — IMMUTABLE LINKS ARCHIVE                              ║
# ║  Permanently logs every recording with all download links to links.txt.    ║
# ║  New entries are prepended (newest first). Entries are never deleted.       ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/utils.sh"

# ═══════════════════════════════════════════════════════════════════════════════
#  UPDATE LINKS ARCHIVE
# ═══════════════════════════════════════════════════════════════════════════════

update_links() {
    log_header "🔗 UPDATING LINKS ARCHIVE"
    
    local stream_title="${STREAM_TITLE:-Unknown Stream}"
    local stream_channel="${STREAM_CHANNEL:-Unknown Channel}"
    local stream_url="${STREAM_URL:-N/A}"
    local duration_fmt="${RECORD_DURATION_FMT:-00:00:00}"
    local size_human="${RECORD_SIZE_HUMAN:-0 B}"
    local size_gb="${RECORD_SIZE_GB:-0.00}"
    local parts="${RECORD_PARTS:-1}"
    local current_date
    current_date=$(now_pkt)
    local upload_count="${UPLOAD_SUCCESS_COUNT:-0}"
    local upload_total="${UPLOAD_TOTAL_SERVICES:-3}"
    
    # ── Build new entry ──────────────────────────────────────────────────────
    log_step "Building links entry..."
    
    local safe_title
    safe_title=$(sanitize_filename "$stream_title")
    
    local entry=""
    entry+="========================================\n"
    entry+="Date:     ${current_date}\n"
    entry+="Title:    ${stream_title}\n"
    entry+="Channel:  ${stream_channel}\n"
    entry+="File:     ${safe_title} (${parts} part(s))\n"
    entry+="URL:      ${stream_url}\n"
    entry+="Duration: ${duration_fmt}\n"
    entry+="Size:     ${size_human} (${size_gb} GB)\n"
    entry+="Uploads:  ${upload_count}/${upload_total}\n"
    entry+="--- Links ---\n"
    
    # Add Gofile links
    if [[ -n "${GOFILE_LINKS:-}" ]]; then
        IFS=';' read -ra g_entries <<< "$GOFILE_LINKS"
        for g_entry in "${g_entries[@]}"; do
            local g_part g_link
            g_part=$(echo "$g_entry" | cut -d'|' -f1)
            g_link=$(echo "$g_entry" | cut -d'|' -f2)
            [[ -n "$g_link" ]] && entry+="[gofile:${g_part}] ${g_link}\n"
        done
    fi
    
    # Add Pixeldrain links
    if [[ -n "${PIXELDRAIN_LINKS:-}" ]]; then
        IFS=';' read -ra p_entries <<< "$PIXELDRAIN_LINKS"
        for p_entry in "${p_entries[@]}"; do
            local p_part p_link
            p_part=$(echo "$p_entry" | cut -d'|' -f1)
            p_link=$(echo "$p_entry" | cut -d'|' -f2)
            [[ -n "$p_link" ]] && entry+="[pixeldrain:${p_part}] ${p_link}\n"
        done
    fi
    
    # Add Archive.org links
    if [[ -n "${ARCHIVE_LINKS:-}" ]]; then
        IFS=';' read -ra a_entries <<< "$ARCHIVE_LINKS"
        for a_entry in "${a_entries[@]}"; do
            local a_part a_link
            a_part=$(echo "$a_entry" | cut -d'|' -f1)
            a_link=$(echo "$a_entry" | cut -d'|' -f2)
            [[ -n "$a_link" ]] && entry+="[archive:${a_part}] ${a_link} (PERMANENT)\n"
        done
    fi
    
    entry+="========================================\n"
    
    log_info "Entry preview:"
    echo -e "$entry" | head -20
    
    # ── Read existing links.txt ──────────────────────────────────────────────
    log_step "Reading existing links.txt..."
    
    local existing_links
    existing_links=$(github_api_read_content "links.txt" 2>/dev/null) || existing_links=""
    
    if [[ -n "$existing_links" ]]; then
        log_info "Existing links.txt: $(echo "$existing_links" | wc -l) lines"
    else
        log_info "No existing links.txt — creating new"
        existing_links="# 📡 Stream Recorder — Links Archive\n# Generated by Automated Stream Recorder v${RECORDER_VERSION:-2.0.0}\n# © ${RECORDER_NAME:-Muneeb Ahmad}\n# Newest entries at the top. Entries are never deleted.\n\n"
    fi
    
    # ── Prepend new entry ────────────────────────────────────────────────────
    log_step "Prepending new entry..."
    
    local new_content
    # Find the header end and insert after it
    if echo -e "$existing_links" | head -1 | grep -q "^#"; then
        # Has header — insert after empty line following header
        local header_end
        header_end=$(echo -e "$existing_links" | grep -n "^$" | head -1 | cut -d: -f1)
        if [[ -n "$header_end" ]]; then
            local header
            header=$(echo -e "$existing_links" | head -n "$header_end")
            local body
            body=$(echo -e "$existing_links" | tail -n +"$((header_end + 1))")
            new_content="${header}\n\n$(echo -e "$entry")\n${body}"
        else
            new_content="$(echo -e "$entry")\n${existing_links}"
        fi
    else
        new_content="$(echo -e "$entry")\n${existing_links}"
    fi
    
    # ── Write to GitHub ──────────────────────────────────────────────────────
    log_step "Saving links.txt to GitHub..."
    
    if github_api_write "links.txt" "$(echo -e "$new_content")" "🔗 New recording: ${stream_title} — $(TZ='Asia/Karachi' date '+%Y-%m-%d')"; then
        log_ok "Links archive updated successfully"
    else
        log_error "Failed to update links.txt"
        return 1
    fi
    
    log_ok "Recording permanently archived in links.txt"
    return 0
}

# ═══════════════════════════════════════════════════════════════════════════════
#  READ LINKS (used by refresh and weekly report)
# ═══════════════════════════════════════════════════════════════════════════════

read_links() {
    github_api_read_content "links.txt" 2>/dev/null || echo ""
}

# ═══════════════════════════════════════════════════════════════════════════════
#  ENTRY POINT
# ═══════════════════════════════════════════════════════════════════════════════

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    update_links
fi
